sudo: required
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install cookiecutter
  - pip install git+https://github.com/qbicsoftware/r-lint-cli

script:
  - cookiecutter --no-input https://github.com/qbicsoftware/r-container-template
  - cd ./QABCD
  - r-lint lint .  

after_success:
  - codecov
